Makefile

/bin/
main

/data/
linkuser.dat
linkticket.dat
linkhistory.dat

/include/
menu.h
function.h
link_user.h
link_ticket.h
link_history.h

/src/
main.c
menu.c
function.c
link_user.c
link_ticket.c
link_history.c